# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='thesisInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='主题')),
                ('headline', models.CharField(max_length=100, verbose_name='摘要')),
                ('keyword', models.CharField(max_length=50, verbose_name='关键词')),
                ('thesisUrl', models.CharField(max_length=200, verbose_name='论文保存地址')),
                ('auditStatus', models.IntegerField(choices=[(1, '通过'), (2, '不通过')], verbose_name='审核状态')),
                ('reviewStatus', models.IntegerField(choices=[(1, '通过'), (2, '不通过')], verbose_name='评审状态')),
                ('creationTime', models.DateTimeField(verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(verbose_name='修改时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
