# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, verbose_name='信息内容')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('meetingInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.MeetingInfo')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='type',
            field=models.IntegerField(choices=[(1, '管理员'), (2, '审稿员'), (3, '参会者')], verbose_name='用户类型'),
        ),
    ]
