# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170422_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginfo',
            name='create_time',
            field=models.DateTimeField(default='2017-4-23', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='create_time',
            field=models.DateTimeField(default='2017-4-23', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='meetingInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.MeetingInfo', verbose_name='会议'),
        ),
        migrations.AlterField(
            model_name='thesisinfo',
            name='create_time',
            field=models.DateTimeField(default='2017-4-23', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='thesisinfo',
            name='thesisUrl',
            field=models.FileField(upload_to='documents/%Y/%m/%d', verbose_name='论文保存地址'),
        ),
    ]
