# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170422_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisinfo',
            name='thesisUrl',
            field=models.FileField(upload_to='/projects/static/documents/%Y/%m/%d', verbose_name='论文保存地址'),
        ),
    ]
