# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20170422_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisinfo',
            name='auditStatus',
            field=models.IntegerField(blank=True, choices=[(1, '通过'), (2, '不通过')], null=True, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='thesisinfo',
            name='reviewStatus',
            field=models.IntegerField(blank=True, choices=[(1, '通过'), (2, '不通过')], null=True, verbose_name='评审状态'),
        ),
    ]
